When text is sleected in rendered contant NoSuchMethodError is raised
This is fixed in recent versions of batik - this commit updates to the
most current one.

java.lang.NoSuchMethodError: 'void java.lang.SecurityManager.checkSystemClipboardAccess()'
	at org.apache.batik.swing.gvt.JGVTComponent$UnixTextSelectionListener.selectionDone(Unknown Source)
	at org.apache.batik.gvt.text.ConcreteTextSelector.dispatchSelectionEvent(Unknown Source)
	at org.apache.batik.gvt.text.ConcreteTextSelector.checkSelectGesture(Unknown Source)
	at org.apache.batik.gvt.text.ConcreteTextSelector.mouseReleased(Unknown Source)
	at org.apache.batik.swing.gvt.TextSelectionManager$MouseListener.mouseReleased(Unknown Source)
	at org.apache.batik.gvt.event.AWTEventDispatcher.processMouseEvent(Unknown Source)